(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'init-settings)
(require 'init-package)
(require 'init-core)
;; (require 'init-lsp)
(require 'init-evil)
(require 'init-languages)
(require 'init-style)
(require 'init-style-extra)
;; (require 'init-style-min)
